[theme]
primaryColor = "#00CC96"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
